/*


    This file is part of WOW! based on AHA! (Adaptive Hypermedia for All) which is free software (GNU General Public License) developed by Paul De Bra - Eindhoven University of Technology and University

    WOW! is also open source software; 


*/
/**
 * NextView.java 1.0, October 19, 2008
 *
 *Copyright (c) 2006 by Eindhoven University of Technology and modified by University of Science, 2008. All Rights Reserved.
 *
 * This software is proprietary information of Eindhoven University of Technology and University
 * of Science. It may be used according to the GNU license of Eindhoven University of Technology
 */

package vn.spring.WOW.Layout;

import vn.spring.WOW.datacomponents.Profile;
import java.io.*;
import java.util.*;
import vn.spring.WOW.engine.*;
import vn.spring.WOW.parser.*;
import vn.spring.WOW.WOWStatic;
import vn.spring.WOW.exceptions.*;

/**
 * This is a view representing the next suitable concept.
 */
public class NextView implements View {

    private String name;
    public String back;
    public String title;
    public String params;
    private SecWndLinks swl;

    /**
     * generates the the Browers code(HTML/XHTML) for the view
     */
    public InputStream genBrsCode(String conceptname, Profile profile, Map params) {
        HTMLAnchor link = new HTMLAnchor();
        String activeconcept = conceptname;
        String course = ""; try {course = profile.getAttributeValue("personal", "course");} catch (Exception e) {e.printStackTrace();}
        Hierarchy hierarchy = WOWStatic.CourseInfoTbl.getCourseInfo(course).hierarchy;
        StringBuffer outstr = new StringBuffer();
        outstr.append("<html>\n<body>\n");
        PNode rnode=new PNode(hierarchy.getTNode(activeconcept), profile);
        PNode snode=null;
        while ((snode==null) && ( (rnode=nextNode(rnode))!=null )) {
            if (suitableConcept(rnode.getName(), profile)) snode=rnode;
        }
        if (snode != null) {
            //found next suitable concept
            outstr.append(link.genLinkTo(snode.getName(), profile));
        } else {
            //no next suitable concept
            outstr.append("end of course");
        }

        InputStream insb = new ByteArrayInputStream(outstr.toString().getBytes());
        return insb;
    }

    private boolean suitableConcept(String cname, Profile profile) {
        UMVariableLocator umvl = new UMVariableLocator(profile, WOWStatic.DB().getConceptDB());
        Object r = null;
        try {
            r = umvl.getVariableValue(cname+".suitability");
        } catch (ParserException e) {
            return false;
        }
        if (r instanceof String) return false;
        else if (r instanceof Float) return ((Float)r).intValue()>0;
        else if (r instanceof Boolean) return ((Boolean)r).booleanValue();
        else return false;
    }

    private PNode nextNode(PNode node) {
        PNode nnode = node.getFirstChild();
        if (nnode != null) return nnode;
        nnode = node.getNextSib();
        if (nnode != null) return nnode;
        nnode = node;
        while (nnode.getParent() != null) {
            nnode = nnode.getParent();
            if (nnode.getNextSib() != null) return nnode.getNextSib();
        }
        return null;
    }

    /**
     * returns the view with name viewName
     */
    public String getViewName() {return name;}

    /**
     * returns the view with name viewName
     */
    public String getViewType() {return "NEXTVIEW";}

    /**
     * returns the Mime type of the response generated by the view
     */
    public String getMime() {return "text/html";}

    public boolean isStatic() {return false;}

    /**
     * returns the name of the Secondary window that is being opened by
     * secondary link 'linkname'
     */
    public SecWndLinks getSecWndLinks() {return swl;}

    public void setSecWndLinks(SecWndLinks swl) {this.swl = swl;}
    public void setViewName(String name) {this.name = name;}
    public void setBackgound(String back) {this.back = back;}
    public void setParams(String params) {this.params = params;}
    public void setTitle(String title) {this.title = title;}
}