/*


    This file is part of WOW! based on AHA! (Adaptive Hypermedia for All) which is free software (GNU General Public License) developed by Paul De Bra - Eindhoven University of Technology and University

    WOW! is also open source software; 


*/
/**
 * View.java 1.0, August 30, 2008
 *
 *Copyright (c) 2006 by Eindhoven University of Technology and modified by University of Science, 2008. All Rights Reserved.
 *
 * This software is proprietary information of Eindhoven University of Technology and University
 * of Science. It may be used according to the GNU license of Eindhoven University of Technology
 */

package vn.spring.WOW.Layout;

import java.util.*;
import vn.spring.WOW.datacomponents.Profile;
import java.io.InputStream;


/**
 * This class represent the internal representation of a view
 */

public interface View {

   /**
   * generates the the Browers code(HTML/XHTML) for the view
   */
   public InputStream genBrsCode(String conceptname, Profile profile, Map params);

   /**
   * returns the view with name viewName
   */
   public String getViewName();

   /**
   * returns the view with name viewName
   */
   public String getViewType();

   /**
   * returns the Mime type of the response generated by the view
   */
   public String getMime();

   /**
   * returns returns true is view needs to be updated when MAIN updated
   */
   public boolean isStatic();

   /**
    * returns the name of the Secondary window that is being opened by
    * secondary link 'linkname'
    */
   public SecWndLinks getSecWndLinks();

   public void setSecWndLinks(SecWndLinks swl);
   public void setViewName(String name);
   public void setBackgound(String back);
   public void setParams(String params);
   public void setTitle(String params);


}