# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.auto", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1196100499);
user_pref("app.update.lastUpdateTime.background-update-timer", 1196100495);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1196100495);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1196100499);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1196100499);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.feeds.handler.default", "bookmarks");
user_pref("browser.feeds.showFirstRunUI", false);
user_pref("browser.places.createdDefaultQueries", true);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
