/*


    This file is part of WOW! based on AHA! (Adaptive Hypermedia for All) which is free software (GNU General Public License) developed by Paul De Bra - Eindhoven University of Technology and University

    WOW! is also open source software; 


*/
/* SaveForm.java 1.0, August 30, 2008
 *
 *Copyright (c) 2006 by Eindhoven University of Technology and modified by University of Science, 2008, Vietnam.
 * All Rights Reserved.
 *
 * This software is proprietary information of Eindhoven University of Technology and University
 * of Science. It may be used according to the GNU license of Eindhoven University of Technology
 */


import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import vn.spring.WOW.WOWStatic;

public class SaveForm extends HttpServlet {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String filename;

    /**
     * Initializes the servlet
     *
     * @param config the <code>ServletConfig</code>
     * @throws ServletException
     */
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
    }

    /**
     * Overrides the <code>service</code> from <code>HttpServlet</code>
     *
     * @param request the <code>HttpServletRequest</code>
     * @param response the <code>HttpServletResponse</code>
     * @throws IOException generated by <code>doPost</code>
     * @throws ServletException when something goes wrong with servlet
     */
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        HttpSession session = request.getSession(true);
        if (session!=null) synchronized(session.getId()) {
            //response.setContentType("text/html;charset=UTF-8");
            filename = request.getHeader("Filename");
            try {
                doPost(request, response);
            } catch (ServletException se) {
                System.out.println(se);
            } catch (IOException ie) {
                System.out.println(ie);
            }
        }
    }

    /**
     * Overrides the <code>doPost</code> from <code>HttpServlet</code>
     *
     * @param request the <code>HttpServletRequest</code>
     * @param response the <code>HttpServletResponse</code>
     * @throws IOException when something goes wrong with writing to file
     * @throws ServletException when something goes wrong with servlet
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response) throws java.io.IOException, ServletException {
        filename = WOWStatic.config.Get("XMLROOT")+WOWStatic.FORMPATH+filename;
        response.setContentType("text/html;charset=UTF-8");
        File file=new File(filename);
        try {
            FileWriter out = new FileWriter(file);
            out.write(request.getParameter("xmlfile"));
            out.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}